name: Deploy to EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: i-05fb70fb7cdebbb77
          username: ubuntu
          script: |
            # Step 1: Connect to the EC2 instance
            cd ~

            # Step 2: Check if the aws-OctaOcean directory exists and delete it if it does
            if [ -d "aws-OctaOcean" ]; then
              rm -rf aws-OctaOcean
            fi

            # Clone the aws-OctaOcean repository
            git clone https://github.com/NyanCyanide/aws-OctaOcean.git

            # Step 3: Copy files from the build folder to /var/www/html and /var/www/OctaOcean/html
            sudo cp -r aws-OctaOcean/build/. /var/www/html/
            sudo cp -r aws-OctaOcean/build/. /var/www/OctaOcean/html/

            # Step 4: Restart nginx server
            sudo systemctl restart nginx

            # Step 5: Install node packages and run server
            cd aws-OctaOcean/server
            npm install
            node index.js
